config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews
  end 
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :place_pic, styles: { place_index: "350x350>", place_show: "350x350>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :place_pic, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :find_restaurant, only:[:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only:[:new, :edit]

    def index
        if params[:category].blank?
            @restaurants = Restaurant.all.order("created_at DESC")
       else
           @category_id = Category.find_by(name: params[:category]).id
           @restaurants = Restaurant.where(:category_id => @category_id).order("created_at DESC")
       end
    end

    def new
        @restaurant = current_user.restaurants.build
        @categories = Category.all.map{|c| [c.name, c.id]}
    end

    def show
        if @restaurant.reviews.blank?
            @average_review = 0
        else
            @average_review = @restaurant.reviews.average(:rating).round(2)
        end
    end

    def create
        @restaurant = current_user.restaurants.build(restaurant_params)
        @restaurant.category_id = params[:category_id]

        if @restaurant.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @categories = Category.all.map{|c| [c.name, c.id]}
    end

    def update
        @restaurant.category_id = params[:category_id]
    if 
        @restaurant.update(restaurant_params)
        redirect_to restaurant_path(@restaurant)
    else
        render 'edit'
    end

    end



    def destroy
        @restaurant.destroy
        redirect_to root_path
    end

    private

    def restaurant_params
        params.require(:restaurant).permit(:name, :address, :phone, :description, :category_id, :place_pic)
    end

    def find_restaurant
        @restaurant = Restaurant.find(params[:id])
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_restaurant
    before_action :find_review, only: [:edit, :update, :destroy] 
    before_action :authenticate_user!, only:[:new, :edit]

    def new 
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.restaurant_id = @restaurant.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to restaurant_path(@restaurant)
        else
            render 'new'
        end
    end 

    def edit

    end 

    def update

        if @review.update(review_params)
            redirect_to restaurant_path(@restaurant)
        else 
            render 'edit'
    end
end

def destroy 
    @review.destroy
    redirect_to restaurant_path(@restaurant)
end

    private
    def review_params
        params.require(:review).permit(:rating, :comment)
    end

    def find_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NATUR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script data-ad-client="ca-pub-8249422972122368" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
     
     <div class="container">
     
      <div class="navbar-header" >
         <%= link_to "NATUR", root_path, class: "navbar-brand"%>
      </div>

      <ul class="nav navbar-nav">
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to "Log in", new_user_session_path %> </li>  
          <% end %>
          <% if user_signed_in? %>
      <li> <%= link_to "Add place", new_restaurant_path %></li>
      <% end %>
      
      </ul>
       

    <ul class="nav navbar-nav navbar-right">

    <li class="dropdown" >
      <a href="#" class="dropdown-item" data-toggle="dropdown" role="button"  
      aria-expanded="false"> Categories <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu"> 
        <% Category.all.each do |category| %>
          <li classs="<%= 'active' if params[:category] == category.name%>">
            <%= link_to category.name, restaurants_path(category: category.name), class: "link"%>
          </li>
        <% end %>
      </ul>
    </li>

      
      </ul>
      
      </div>
   </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
     <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant, :html => {:multipart => true} do |f| %>
<%= select_tag(:category_id, options_for_select(@categories))%>
<%= f.file_field :place_pic%>
<%= f.input :name, label: "Restaurant name" %>
<%= f.input :address %>
<%= f.input :phone %>
<%= f.input :description %>
<%= f.button :submit, :class=> 'btn-custom2'%>

<% end %>

app/views/restaurants/edit.html.erb
<div class="col-md-6 col-md-offset-3 ">
<div class="edit-restaurant-form">

<h1>Edit Restaurant</h1>
<%= simple_form_for @restaurant, :html => {:multipart => true} do |f| %>
<%= f.select :category_id, @categories %>
<%= f.input :name, label: "Restaurant name" %>
<%= f.input :address %>
<%= f.input :phone %>
<%= f.input :description %>
<%= f.button :submit, :class=>"btn-custom2" %>

<% end %>
</div>
</div>

app/views/restaurants/index.html.erb
<h1 class="current-category"> <%= params[:category]%> </h1>

<%if @restaurants.count == 0%>
    <h1> No restaurants in this category </h1>
    
 <%else%>

 <div class="row">
  <%  @restaurants.each do |restaurant| %>
   <div class="col-md-3">
   <a href="/restaurants/<%= restaurant.id %>">
      <%= image_tag restaurant.place_pic.url(:place_index), class: "restaurant"  %>
   </a>
   </div>
   <% end %>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<div class="col-md-6 col-md-offset-3 ">
<div class="new-restaurant-form">
 <h1>New restaurant</h1>

 <%= render 'form'%>
</div>
</div>

app/views/restaurants/show.html.erb
<div class="row">

 <div class="col-md-4">
  <%= image_tag @restaurant.place_pic.url(:place_show), class: "restaurant-show" %>
  </div>

  <div class="col-md-8"> 
  <div class="restaurant-info">
  <h2 class="restaurant-name"> <%= @restaurant.name %> </h2>
  <h5 class="restaurant-phone"> Phone: <%= @restaurant.phone %> </h5>
  <h5 class="restaurant-address"> Address: <%= @restaurant.address %> </h5>
  <h5> Category: <%= @restaurant.category.name %> </h5>
  <h2 class="avg-rating"> Average rating</h2>
  <div class="average-review-rating" class="glyphicon glyphicon-star" data-score="<%= @average_review %>">
  
  </div>
  <span class="number-of-reviews"> Based on <%= @restaurant.reviews.count %> Reviews </span>
  <p class="restaurant-desc"> <%= @restaurant.description %> </p>

</div>
</div>
</div>

<div class="row">
    <div class="col-md-4">

      <div class="reviews">
       <h1> Reviews </h1>
         <!-- where the reviews/ratings go -->
          <%= render @restaurant.reviews %>
         <div>
         <%= link_to "Add Review", new_restaurant_review_path(@restaurant), class:"btn-custom" %>
        </div>
    </div>

    </div>

</div>

<div class="links btn-group">
<%= link_to "Back", root_path, class:"btn btn-custom" %>

<% if user_signed_in? %>

<% if @restaurant.user_id == current_user.id %>
    <%= link_to "Edit", edit_restaurant_path(@restaurant), class:"btn btn-custom"%>
    <%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: {confirm: "Sure you want to delete it?"}, class:"btn btn-custom"%>

    <%end%>

<%end%>
</div>

<script>
  
jQuery(function() {
    $('.review-rating').raty({
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '../assets/'
    });
});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
	  path: '../assets/',
	 	score: function() {
 		return $(this).attr('data-score')
 	}
 });
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @restaurant.reviews.build]) do |f|%>
<div id="star-form">
 <label> Rating </label>
</div>


<%= f.input :comment %>
<%= f.button :submit, class: "btn-custom2" %>
<% end %>

<script>
	$('#star-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">


<div class="review-rating"  data-score="<%= review.rating %>"> 
          
</div>

<p class="review-comment"> <%= review.comment  %> </p>

<% if user_signed_in?%>
 <% if review.user_id == current_user.id%>

   
      <div class="links btn-group">
            <%= link_to "Edit", edit_restaurant_review_path(review.restaurant, review), class:"btn btn-custom" %>
            <%= link_to "Delete", restaurant_review_path(review.restaurant, review), method: :delete, data: {
            confirm: "Are you sure?" }, class:"btn btn-custom" %>
      </div>
 <% end %> 
<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3 ">
<div class="edit-review-form">

<h1>Edit Review</h1>
<%= simple_form_for([@restaurant, @review]) do |f| %>
<div id="rating-form">
 <%= f.input :rating %>
</div>
 <%= f.input :comment %>
 <%= f.button :submit, class:"btn-custom2" %>
<% end %>
</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/javascript/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3 ">
<div class="new-review-form">

<h1>New review</h1>

<%= render 'form'%>

</div>
</div>